# Generated by Django 3.2.19 on 2023-05-09 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshift',
            old_name='role',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='ShiftBooking',
        ),
    ]
