# Generated by Django 3.2.19 on 2023-05-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
