# Generated by Django 3.2.19 on 2023-05-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_workshift_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshift',
            name='name',
            field=models.CharField(default='Location', max_length=100),
        ),
    ]
