# Generated by Django 3.2.19 on 2023-05-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_alter_workshift_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
