# Generated by Django 3.2.18 on 2023-05-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_workshift_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshift',
            name='users',
        ),
        migrations.AddField(
            model_name='workshift',
            name='event',
            field=models.CharField(default='event', max_length=100),
        ),
    ]
