# Generated by Django 3.2.18 on 2023-05-22 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_auto_20230522_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshift',
            old_name='name',
            new_name='location',
        ),
    ]
