# Generated by Django 3.2.18 on 2023-05-22 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0010_rename_name_workshift_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshift',
            name='event',
            field=models.CharField(default='Event', max_length=100),
        ),
        migrations.CreateModel(
            name='CancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workshift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.workshift')),
            ],
        ),
    ]
