# Generated by Django 3.2.18 on 2023-05-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_auto_20230522_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='is_cancel_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workshift',
            name='is_cancel_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CancellationRequest',
        ),
    ]
