# Generated by Django 3.2.18 on 2023-05-22 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0012_auto_20230522_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshift',
            name='is_cancel_approved',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='is_cancel_requested',
        ),
    ]
