# Generated by Django 3.2.20 on 2023-08-10 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_auto_20230522_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='shift_details',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(400)]),
        ),
    ]
