# Generated by Django 3.2.19 on 2023-05-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_auto_20230509_0044'),
        ('profiles', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shifts',
            field=models.ManyToManyField(related_name='booked_users', to='scheduling.WorkShift'),
        ),
    ]
