# Generated by Django 3.2.19 on 2023-05-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_shifts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='shifts',
            new_name='booked_workshifts',
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
