# Generated by Django 3.2.19 on 2023-05-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_workshift_is_booked'),
        ('profiles', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='booked_workshifts',
            field=models.ManyToManyField(related_name='booked_by', to='scheduling.WorkShift'),
        ),
    ]
