# Generated by Django 3.2.19 on 2023-05-10 22:11

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20230510_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.upload_to),
        ),
    ]
