# Generated by Django 3.2.19 on 2023-05-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='work_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
