# Generated by Django 3.2.19 on 2023-05-13 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(400)]),
        ),
    ]
