# Generated by Django 3.2.19 on 2023-05-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_workshift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshift',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
