# Generated by Django 3.2.20 on 2023-08-10 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_workshift_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='users',
        ),
    ]
