# Generated by Django 3.2.20 on 2023-08-10 21:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0007_remove_booking_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='users',
            field=models.ManyToManyField(related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
