# Generated by Django 3.2.20 on 2023-08-10 23:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0009_booking_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshift',
            name='users',
        ),
        migrations.AddField(
            model_name='workshift',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_shifts', to=settings.AUTH_USER_MODEL),
        ),
    ]
