# Generated by Django 3.2.19 on 2023-05-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_workshift'),
        ('authentication', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='booked_workshifts',
            field=models.ManyToManyField(related_name='booked_users', to='booking.Booking'),
        ),
    ]
