# Generated by Django 3.2.19 on 2023-05-09 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userprofile_booked_workshifts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='booked_workshifts',
        ),
    ]
